### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by consensyx** [ont/rshell#1]
Hello

i notice you didn't leave your email in your profile, i am  very sorry about to open the issue to contact you, actually, i want use the "ont" as my github user name, if you are willing to change, i can pay some fee for you(like ether or other).

My Email: xriswho@gmail.com, looking forward your reply.

**Comment by ont** [comment]
No, I don't want to change my nickname :)  Sorry about that.

**Comment by xris-hu** [comment]
I am sorry to bother you, i know you love your nickname, but can you think it about again?, Can you give a number that make you to change your decision?  i am seriously.
